### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by froger-me** [remicaumette/dofustouch-emu#1]
Hello
What to do at each new version? The game wouldn't launch.
<img width="536" alt="screen shot 2017-03-27 at 10 35 47 am" src="https://cloud.githubusercontent.com/assets/3622456/24338662/b5a486d6-12d9-11e7-9636-f2c58f11584f.png">

**Comment by remicaumette** [comment]
Hi, this project is now longer supported, there are no new update. If you want update him manually you can (change dofus script and ui folder).

**Comment by froger-me** [comment]
Hi! Thank you for the reply. Would you be able to indicate a procedure to do just that? Where can I find dofus script and UI folder? (both the destination folders, and the files)

**Comment by remicaumette** [comment]
Pour mettre a jour le jeu il suffit de telecharger le nouveau script et de le mettre dans le dossier du jeu qui se situe dans l'application (clique droit contenu du package). Si tu n'y arrives pas je mettrai ca a jour ce soir.

**Comment by froger-me** [comment]
ok, je pourrais voir les diffs pour la destination - mais les scripts ("telecharger le nouveau script"), la source? dans l'APK officiel ou bien?

**Comment by remicaumette** [comment]
Ouai, tu pourras regarder dans les commits.

**Comment by Yumidarka** [comment]
Salut je n'arrive pas à mettre à jour le logiciel je suis sur Windows peut tu mette la démarche à suivre ou me dire où je peut trouver la démarche à suivre àfin de mettre à jour le client

**Comment by Squalalah** [comment]
Bonjour, étant en étude de développement en Info (web et lourd), je souhaitais avoir + amples informations sur le fonctionnement de l'émulateur si possible.

Merci de ta répondre @remicaumette, bonne journée !

Squalalah

**Comment by gaiamoon** [comment]
Hi, i need to know how to update the dofus version, where u get the dofus.js?

**Comment by remicaumette** [comment]
Finally I'm do an update today. 😏

**Comment by Yumidarka** [comment]
vers quel heure

**Comment by Infmeren** [comment]
I need to know how download the script from the apk of dofus :(

**Comment by remicaumette** [comment]
Je viens de rentrer des cours. Ce soir vers 22h il y aura quelque chose je pense 😄 . Si vous avez des questions n'hésiter pas.

**Comment by Yumidarka** [comment]
moi je voudrait savor comment on fait les maj manuellement

**Comment by Infmeren** [comment]
Thanks remi, i have the curiosity that how u convert a apk to javascript, I descompressed the apk and just sawa cordova js that i dont understand very good XD

**Comment by remicaumette** [comment]
@Yumidarka je suis actuellement en train de faire les mises à jour et changer 2/3 trucs. Une release sera bientot disponible (quelques heures).
@Infmeren Hi, I don't convert the apk ^^. I just take dofus touch files only.

**Comment by Yumidarka** [comment]
non mais je demande pour la prochaine fois

**Comment by remicaumette** [comment]
je vais faire une release rapidement pour que tout le monde puisse jouer et après je vais essayer de faire un système de mise à jour automatique.

**Comment by Squalalah** [comment]
Pour mettre a jour toi meme, (et si tu veux le faire avec ton telephone, il faut qu'il soit rooté). Faut acceder aux données du jeu (Data/Data/Com.Ankama blabla...) Et choper le .js, entre autres

**Comment by Yumidarka** [comment]
en tout cas merci pour ton temps et ton travail ^^

**Comment by remicaumette** [comment]
@Squalalah j'ai jamais regardé avant j'utiliser les fichiers dofus de dofus no emu :/. Et si je dois lancer l'application ca risque d'être difficile car j'ai un iphone 👎 .

**Comment by Squalalah** [comment]
Excuse moi, le message était pour @yumi, toi je me fais pas de soucis vu que ta premiere version fonctionnait

**Comment by Infmeren** [comment]
Can u tell the process that u use to get the apk files? D:

**Comment by Squalalah** [comment]
@remicaumette ha je viens de comprendre ton msg en gros tu sais pas cmt recup le .js ?

Si cest le cas au pire, DL un emulateur android que tu peux rooter, installe dofus touch dessus puis tu t'upload le .js de Data/data/com.dofustouch.ankamablablabla

**Comment by remicaumette** [comment]
j'ai deja trouvé le lien mais me manque le lien du script.js (https://proxyconnection.touch.dofus.com/)

**Comment by Squalalah** [comment]
je suis en train d'essayer de te recup le script.js

**Comment by remicaumette** [comment]
merci 👍. actuellement je cherche un moyen de récuperer les fichiers sans l'apk.

**Comment by LYushan** [comment]
https://proxyconnection.touch.dofus.com/build/script.js

**Comment by remicaumette** [comment]
@LYushan merci

**Comment by Squalalah** [comment]
Timing parfait, la solution était déjà abordé sur google haha

**Comment by remicaumette** [comment]
maintenant faut patcher les ce qui va pas pour que le jeu ce lance :)

**Comment by remicaumette** [comment]
Par contre avec ce genre de chose http://www.dofus-touch.com/fr/mmorpg/actualites/news/666422-fermeture-dofus-touch-no-emu le repo va se faire takedown rapidement donc il va falloir trouver une technique :)

**Comment by Squalalah** [comment]
Si tu veux éviter ce genre de choses, plusieurs solutions :

- Avoir un repo de secours caché
- Éviter de proposer des fonctionnalités abusives (comme la fait Dofus no emu d'ailleurs)

En gros, proposer un service identique à dofus touch mobile, rien de + ou de -, déjà ça, ça va réduire tes chances de takedown.

**Comment by remicaumette** [comment]
Oui, cependant l'intérêt de dofus touch sur pc c'est avant tout le multi-compte 😭

**Comment by Squalalah** [comment]
@remicaumette

Et la 2e raison du shutdown d'Ankama est le multi-compte.

Cependant, ce n'est pas uniquement la raison, je ne compte pas les gens qui peuvent soit pas le faire tourner, soit dans des mauvaises conditions, soit car cest pas pratique (taille d'ecran oblige).

Au final, l'utilisation de Dofus Touch n'est pas uniquement tourné vers le multi-compte.

Après, tu fais ce que bon te semble, juste pour te dire que + tu respecteras la volonté d'Ankama, + ils seront clément

**Comment by remicaumette** [comment]
@Squalalah Tu as raison mais je pense qu'il faudrait en discuter avec eux. Le problème c'est qu'ils risquent d'être réfractaire à toute discussion 👎 .

**Comment by Yumidarka** [comment]
non moi je joue sur PC car j'ai pas de tablette et mon ecran de telephone est trop petit

**Comment by Squalalah** [comment]
@remicaumette

Évidemment, je pense pas qu'ils soient contre les émulateurs, mais seulement contre ceux qui donnent des avantages par rapport a la version mobile.

La preuve, sur dofus desktop tu peux multi-compte car n'importe qui peut ouvrir une deuxieme tab pour dofus.

Cependant, Dofus Touch, étant une app mono-compte, ils veulent absolument que ca soit respecté.

Bon après comme déjà dit, dofus no emu a aussi largement été fermé pour le fait de la génération d'argent par un statut VIP, ce qui est completement degueulasse

**Comment by Squalalah** [comment]
D'ailleurs, la premiere raison est le non respect de leurs CGU, mais ca c'est évident car l'entreprise a "l'obligation" de se prémunir, cependant la grosse majorité sont assez tolérant tant que cela introduit pas d'avantages et que ça reste au stade de copie mirroir

**Comment by remicaumette** [comment]
J'ai push sur develop (https://github.com/remicaumette/dofustouch-emu/tree/develop)

**Comment by Squalalah** [comment]
Malheureusement, je ne peux pas t'aider je n'ai pu de pc (windows) depuis un bout de temps (jai juste pu faire un vieux C/C rapidz genial lol), du coup jpeux pas t'aidr.

**Comment by LYushan** [comment]
En réalité c'est pas le multi compte qui gène tant mais les 2800€ récolté en 1 mois sur Tippee ainsi que les fonctionnalité dit VIP qui permettait de simuler le déplacement de tous ses personnages par exemple (Tel un bot socket)

**Comment by remicaumette** [comment]
@LYushan Effectivement quand on commence à gagner autant ^^. Et c'est vrai que les fonctionnalités étaient overcheat.
@Squalalah moi aussi je pas sur windows ^^ (mac). Je vais essayer de trouver la solution.

**Comment by Squalalah** [comment]
D'ailleurs, tu utilises quel outil pour assembler les fichiers sources ? Histoire que je sache car jver essayer de passer en mode ninja sur un win10

**Comment by remicaumette** [comment]
cad ?

**Comment by Squalalah** [comment]
@remicaumette

Avec quoi tu lances l'emu, avec le script direct ou bien tu assembles le tout ?

**Comment by remicaumette** [comment]
Le script, j'assemble tout uniquement quand le build pour la release.

**Comment by Squalalah** [comment]
"la connexion a échoué" ok

**Comment by remicaumette** [comment]
Ouai j'ai le même problème ca veut dire que il sait que le client n'est pas legit.

**Comment by Squalalah** [comment]
Le pb n'était pas là avant, donc le probleme vient de dofus.js très certainement

**Comment by Squalalah** [comment]
T'as fais une recherche de "refused" dans dofus.js ?

J'ai trouvé quelques truc interessant surtout aux "new Error", apres faut comprendre le code.

**Comment by remicaumette** [comment]
@Squalalah bas il te refuse la connexion comme ca donc il détecte que c'est pas le vrai client mais comment ?

**Comment by Squalalah** [comment]
Je sais pk, ils ont interdit l'accès à proxyconnection directement

**Comment by Squalalah** [comment]
Heu non att jai acces via mobile donc pas possible

**Comment by remicaumette** [comment]
normalement l'émulateur marche, cependant je n'arrive pas a créer les applications (pour windows, mac...)

**Comment by Squalalah** [comment]
Quel est le soucid

**Comment by Squalalah** [comment]
D'ailleurs sur le pc jme tape toujours l'erreur de la connexion impossible, ptet que jai pas pull jpense

**Comment by remicaumette** [comment]
ouai je pense car moi ca marche

**Comment by Squalalah** [comment]
Jai get le repo sur le w10, jai lancé via le html mais non je me fais jarter a chaque fois hmm. Apres jai pris en fonction de ton dernier commit sur master.

**Comment by remicaumette** [comment]
C'est bizarre car j'ai retesté pourtant. Demain créé les applications pour chaque os donc si ça ne te dérange pas d'attendre demain 😃 .

**Comment by Squalalah** [comment]
Non ça me dérange pas, j'étais uniquement là pour voir si jpouvais t'aider (code ou bug comme la) :D

**Comment by Squalalah** [comment]
@remicaumette j'ai un autre pote qui vient d'essayer avec son mac et il s'est fait jeté aussi.

**Comment by remicaumette** [comment]
Je regarde tout ca demain. Si tu as les erreurs ca pourra m'avancer.

**Comment by Squalalah** [comment]
"Connexion au serveur échoué" pour ce qui s'agit du message.

**Comment by sudogooglex** [comment]
Marche nickel chez moi. Electron se lance correctement apres avoir téléchargé les dépendances avec npm install. Testé le 28.03.2017, 01:10, Ubuntu 16.10, node v6.2.2

**Comment by Yumidarka** [comment]
je n'y connais pas grand chose en programmation et je sais pas si sa peut vous aide mais on peut tjr ce connecter sur dofus touch via le client dofus touch no emu je l'utilise a l'heure ou j'ecrit ce message

**Comment by remicaumette** [comment]
Oui pour le moment mais jeudi on va bien rigoler 😂😂.

**Comment by Yumidarka** [comment]
oui je sais que jeudi sa ne marchera plus

**Comment by Squalalah** [comment]
Connexion refusée aussi pour mon pc sous Win7

**Comment by Squalalah** [comment]
https://image.noelshack.com/fichiers/2017/13/1490723476-dd.png

**Comment by froger-me** [comment]
fonctionne très bien si rebuild depuis les sources chez moi...

**Comment by remicaumette** [comment]
@Squalalah Je vais upload une release la :)

**Comment by remicaumette** [comment]
Je viens de [faire la release](https://github.com/remicaumette/dofustouch-emu/releases/tag/v1.1.2). Si vous avez d'autre questions/problèmes vous pouvez [ouvrir une issue](https://github.com/remicaumette/dofustouch-emu/issues/new) ou [rejoindre le discord](https://discord.gg/9pdaT).
