### ISSUE TITLE
Interface d'élevage

### ISSUE THREAD

**Issue by Haarkan** [remicaumette/dofustouch-emu#11]
![image](https://cloud.githubusercontent.com/assets/23135793/24514387/68623bdc-1574-11e7-8573-369e11d969ad.png)
Yo ! Petit soucis dans l'interface d'élevage, on dirait que la texture des boutons n'est pas chargée.

**Comment by remicaumette** [comment]
Effectivement, je m'en occupe. Normalement ce soir c'est bon 👍

**Comment by Haarkan** [comment]
D'acc merci ! J'vais essayer de me pencher sur le problème pour te faire gagner du temps mais j'ai jamais touché à électron je te garantis pas une rapidité exceptionnelle ;)

**Comment by remicaumette** [comment]
Dans tout les cas le probleme est réglé, une release sera dispo ce soir :)

**Comment by remicaumette** [comment]
Patch dans la version 1.2.0 👍
