### ISSUE TITLE
problème mise à jour

### ISSUE THREAD

**Issue by blakata** [remicaumette/dofustouch-emu#13]
![image](https://cloud.githubusercontent.com/assets/26792161/24545933/86a6b736-1609-11e7-8bb3-bc005a49e51b.png)
bug lors de la MAJ, j'ai bien mis les fichiers js / css et le dossier ui là ou il faut mais certains fichiers ne sont pas trouvés :(

**Comment by remicaumette** [comment]
Normal, regarde dans le readme comment il faut faire pour installer les sources de dofus touch.

**Comment by blakata** [comment]
j'ai fais exactement comme ca et pourtant ca me marche pas

**Comment by remicaumette** [comment]
T'as fait npm run dofus:install ?

**Comment by blakata** [comment]
j'ai la version du master donc ça ne marche pas

**Comment by remicaumette** [comment]
passe sur develop ;-) (git checkout develop)

**Comment by blakata** [comment]
ok ;) mais c'est normal que ça ne marche pas avec master ?

**Comment by remicaumette** [comment]
Oui, c'est une ancienne version. Dans tout les cas develop sera merge sur master ce soir.

**Comment by blakata** [comment]
ok merci
