### ISSUE TITLE
Entrées `undefined` interactions joueurs

### ISSUE THREAD

**Issue by HorlogeSkynet** [remicaumette/dofustouch-emu#17]
![](https://puu.sh/v5XkD/ea78309346.png)

**Comment by remicaumette** [comment]
Même bug mais quand on relance l'ému il y est plus :/

**Comment by HorlogeSkynet** [comment]
Pas chez tout le monde apparemment 😄 
Nous il y est encore après un reboot...

**Comment by remicaumette** [comment]
J'arrive pas à trouver la cause, rien dans la console, du ankama pur et dur lol

**Comment by Infmeren** [comment]
I solved this with:
.multiCraftMenu{
    display: none;
}

**Comment by remicaumette** [comment]
@Infmeren C'est pas vraiment une super correction de bug x)

**Comment by Infmeren** [comment]
Nu xDD
