### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kamikazouu123** [remicaumette/dofustouch-emu#18]
The %pos% dosen't work theres a problem with it also when you try to mark a cell in the fight it does the same thing 
![dofustitre](https://cloud.githubusercontent.com/assets/26843023/24581975/ffdd7cb2-1725-11e7-922f-dfada4be7778.png)

**Comment by remicaumette** [comment]
It's an ankama bug
Discord:
```
[Dodge] Fan***** - Hier à 10:29
%pos% command and [ping] in battle is broken
[Nyom] - Hier à 10:30
Yeah we know it, dev work on it.
```

**Comment by kamikazouu123** [comment]
ow ok sorry for double post
