### ISSUE TITLE
Supprimer -> multi-compte

### ISSUE THREAD

**Issue by Squalalah** [remicaumette/dofustouch-emu#2]
Yop !

J'ai vu que ton readme renseignait une fonctionnalité de "Multi-Compte" je te conseille de supprimer cette fonctionnalité pour t'éviter la foudre d'Ankama.
Ils ont "sanctionnés" Dofus no-emu car ils généraient de l'argent et donnaient des avantages abusif par rapport à la version mobile, du coup, je pense qu'il serait bon de t'éviter de potentiels problemes etant donné que ton ému est fonctionnelle (suffit semble-t-il de modifier 1 ou 2 trucs pour update le jeu)

**Comment by remicaumette** [comment]
Salut, je viens de voir ça je ne savais pas qu'ils avaient fermé. Je vais supprimer la fonctionnalité de script mais pour le moment je laisse le multi compte. Si tu as d'autres suggestions/conseils/questions n'hésite pas 😄 .
