### ISSUE TITLE
Requête à propos des fichiers son

### ISSUE THREAD

**Issue by Ryderflo** [remicaumette/dofustouch-emu#20]
Bonjour Rémi, 
Déjà bravo pour l'émulateur, j'ai été impressionné sur le fait que l'émulateur soit entièrement de ta création et non une pâle copie du défunt DofusNoEmu qu'on connait tous.
J'aurais une requête peut-être un peu anecdotique à première vue mais qui m'intéresserait particulièrement et qui amènerait un + à l'expérience de jeu.  
Je m'explique, je me suis penché sur le sujet de pouvoir insérer/remplacer des musiques du jeu, j'ai remarqué que la version Android ne gardait aucune trace des musiques dans les dossiers alors qu'IOS si.
Je pense donc qu'il devrait être faisable de pouvoir les remplacer aisément mais comment ?
J’espère que vous éclairerez ma lanterne la dessus, voir que vous trouviez la solution, merci d'avance !

**Comment by HorlogeSkynet** [comment]
Effectivement les musiques sont distantes et apparemment récupérées au fur et à mesure, MAIS, en "insérer/remplacer" comme tu dis ne serait pas altérer le jeu ?

Ces plateformes de "non-émulation" existent dans le seul but de proposer un nouvel environnement d'exécution plus agréable que les petits écrans, mais à aucun moment de _tweaker_ le jeu ou d'y ajouter des fonctionnalités.
Il faudra voir ce qu'en pense @remicaumette, mais cette issue sera très sûrement _closed_ à son réveil, car non-compatible avec les directives fixées.

**Comment by Ryderflo** [comment]
Je ne pense pas que le tweaker serait vraiment l'altérer au sens néfaste, regarde le principe de mods pour par exemple Elder Scrolls V : Skyrim ou je ne sais pas Falllout 4 par exemple, les modifications rendent le jeu meilleur quand elles sont bien faites.
Si l'auteur ne souhaite pas l'implémenter au projet mais simplement qu'il puisse éclairer ma lanterne sur le sujet et me proposer par exemple une solution pour mon usage personnel uniquement ça me conviendra amplement, j'en conviens que ça ne plaît peut être pas à tout le monde en effet.
Mais merci pour ta réponse.

**Comment by remicaumette** [comment]
Salut, tout d'abord merci de l'interêt que tu portes à DofusTouchEmu. Pour ce qui est des changements des musiques, c'est un peu compliqué car ankama ne donne pas la liste de toutes les musiques directement. Par contre tu peux très bien t'amuser par contre à remplacer une par une chaque nouvelle musique tu entends dans dofus :-) (mais ca va être un peu long).
Voila si tu as d'autre questions n'hésite pas à réouvrir une issue ou à revenir sur discord.
Bonne journée Rémi 👍 .
