### ISSUE TITLE
Bug sortie de combat en mode tactique

### ISSUE THREAD

**Issue by Haarkan** [remicaumette/dofustouch-emu#22]
Salut,
Lorsqu'on sort d'un combat avec le mode tactique activé la map freeze comme ceci :
![image](https://cloud.githubusercontent.com/assets/23135793/25287616/55178f82-26c2-11e7-9296-b76b0d3471e7.png)
Idem si lors de la désactivation du mode tactique en combat

**Comment by remicaumette** [comment]
Salut, sans logs je peux pas trop t'aider 👎
