### ISSUE TITLE
New windows

### ISSUE THREAD

**Issue by kihw** [remicaumette/dofustouch-emu#24]
Hello ,
When i would open windows i have an error i guess it's electron but im not sure, 
In menu if you can add  a new menu for new windows it's  cool ;)
I try to add shortcut for move ;)

**Comment by remicaumette** [comment]
Hi, what's the branch you're running ?

**Comment by kihw** [comment]
i talk about menu 
when i click say me error on function : newGameWindow()
And now i can't move , i click and i  go always on 1cellid

**Comment by remicaumette** [comment]
Normal c'est un bug. Je t'invite à changer de branche et à utiliser [celle la](https://github.com/remicaumette/dofustouch-emu/tree/react).

**Comment by kihw** [comment]
Même erreur avec cette branche. Mais y'a un code d'erreur electron : [7060:0725/094225.308:ERROR:gles2_cmd_decoder.cc(9636)] [.Offscreen-For-WebGL-0000024A610B0050]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
Et y'as une erreur dans le index.html pour le fichier css et js.

**Comment by kihw** [comment]
Même problème pour les déplacements avec ceci venant d'electron :
[10340:0725/095641.853:ERROR:gles2_cmd_decoder.cc(9636)] [.Offscreen-For-WebGL-000001DAB437CA90]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
