### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by lozziali** [remicaumette/dofustouch-emu#25]
Bonsoir,
J'aimerai bien vous contacter par e-mail, Facebook ou par le moyen que vous préférez.
Est-ce possible? ^^

**Comment by HorlogeSkynet** [comment]
Hello !

Je devance un peu @remicaumette pour te donner une réponse "rapide", mais il te répondrait sûrement de passer par [le serveur Discord qu'il avait créé pour cela](https://discord.gg/GCxBPPZ).

À très bientôt 👋

**Comment by lozziali** [comment]
Mercii Infiniment!!
