### ISSUE TITLE
Emplacement des fichiers

### ISSUE THREAD

**Issue by blakata** [remicaumette/dofustouch-emu#6]
salut, où puis-je trouver les fichiers .html avec un emulateur rooté ? je ne trouve que le .js et .css :/

**Comment by blakata** [comment]
et aussi ou trouver le .js non compacté

**Comment by remicaumette** [comment]
Salut, les fichiers du jeu sont téléchargés directement depuis le site de dofus touch. L'application n'est "que le launcher du jeu" a vrai dire. Si tu as d'autre questions n'hésite pas sinon je t'invite a fermer l'issue :-). Bonne journée Rémi

**Comment by remicaumette** [comment]
Re, pour les fichiers voici les emplacements :
- https://proxyconnection.touch.dofus.com/assetMap.json
- https://proxyconnection.touch.dofus.com/build/script.js
- https://proxyconnection.touch.dofus.com/build/styles-native.css
