### ISSUE TITLE
JS script

### ISSUE THREAD

**Issue by Infmeren** [remicaumette/dofustouch-emu#7]
What do you change on the code of script.js when you download it? O,o changin the version from the old script all works good but when I copy the new script I get this error:
![s](https://cloud.githubusercontent.com/assets/26716555/24504769/c8b8586c-1557-11e7-91f8-1ab9c9f92af5.PNG)

I think that its some error to when the game's init the gui :/

**Comment by remicaumette** [comment]
Hello, I do an update around 15h30 for fix it.

**Comment by CorentinQLF** [comment]
J'attends la mise à jour avec impatience :)

J'espère que cet émulateur va durer dans le temps avec une petite communauté pour ne pas se faire remarqué par Ankama.

**Comment by remicaumette** [comment]
Je viens de rentrer je le mets à jour là :-) . Moi aussi j'aimerai ^^
