### ISSUE TITLE
Discord Invalide

### ISSUE THREAD

**Issue by reda68** [remicaumette/dofustouch-emu#8]
J'aimerai bien rejoindre le discord mais le lien n'est plus valide je voulais savoir si tu pouvais remettre un nouveau lien. 
Merci

**Comment by remicaumette** [comment]
https://discord.gg/GCxBPPZ Ca te ne marche pas ?

**Comment by remicaumette** [comment]
Effectivement le lien n'est plus valide, je vais le mettre a jour. Bonne journée Rémi
