### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by CorentinQLF** [remicaumette/dofustouch-emu#9]
Bonjour,

Voici mes suggestions :

- Notification dès la connexion d'un ami
- Notification lors d'un combat kolizéum trouvé
- Notification lors d'une demande d'échange
- Notification lors d'une demande d'invitation a un groupe / koli / rejoindre une guilde
- Notification lors de la réception d'un message privé

**Comment by Squalalah** [comment]
Vu que je savais pas cmt tu allais gérer les notifs, jter fais une liste des events que j'ai trouvé vite fait, répondant à la problématique :

- FriendWarnOnConnectionStateMessage
- X
- ExchangeRequestedTradeMessage
- PartyJoinMessage ? / X / GuildInvitedMessage
- X

**Comment by remicaumette** [comment]
Je compte passer par une lib electron. Merci pour la liste des events. Je fais ca ce soir. Bonne journée 🤓🐶

**Comment by remicaumette** [comment]
Disponible dans la [dernière release](https://github.com/remicaumette/dofustouch-emu/releases/tag/v1.3.0). Je ferme l'issue 👍
